In this notebook I will be going through the live examples shown in the class 

In [ ]:
'''
This is a long test 
comment 
having uliplt line 
where we can write details about the code 

'''

In [ ]:
'''Yes, in Jupyter Notebook, you can switch between tabs (also known as cells)
 using keyboard shortcuts. The default shortcuts may vary slightly depending on your browser an
 d operating system, but typically you can use:
'''

In [ ]:
'''but if you write any code in 
the same cell this 
will be treated as comment '''
print('Comment')

'''Yes, in Jupyter Notebook, you can switch between tabs (also known as cells) using keyboard shortcuts. The default shortcuts may vary slightly depending on your browser and operating system, but typically you can use:'''

In [ ]:
int(float("56.7"))


In [ ]:
print(type(2*1.5))

# defining a function
def function_name(parameter):
    '''doctring defining what the functtion does'''
    body
    return

using a function 
function_name(arguments)

In [ ]:
hot = 22

In [32]:
def c_to_f(c):
    '''This function takes an argumnet in
      Degrees Celsius and returns the temperature in Fahrenhiet'''
    f = 9/5*float(c) + 32

    return f 

assert c_to_f(0) == 32.0
#hot =  c_to_f(20)
print("Test Passes")

Test Passes


In [ ]:
help(c_to_f)

Can we use a function wich return a value e.g. our c_to_f function with assert 

In [41]:
'This string \t is Hoda\'s string \\using \"escape\" \n squence'

'This string \t is Hoda\'s string \\using "escape" \n squence'

In [42]:
'This string is Hoda\'s string \\using \"escape\" squence'

'This string is Hoda\'s string \\using "escape" squence'

In [44]:
'This string is Hoda\'s string using \"escape\" squence'

'This string is Hoda\'s string using "escape" squence'

In [40]:
print('This string \t is Hoda\'s string \\using \"escape\" \n squence')

This string 	 is Hoda's string \using "escape" 
 squence


In [6]:
number = [1,10, 100, 1000, '10000']
for i,v in enumerate(number):
    print(type(i), type(v))

<class 'int'> <class 'int'>
<class 'int'> <class 'int'>
<class 'int'> <class 'int'>
<class 'int'> <class 'int'>
<class 'int'> <class 'str'>


In [10]:
a = [1,2,3,4,5,6,7]
b = [4,5,6]
c = ('a','b','c', 'd')

for i,j,k in zip(a,b, c):
    print(i,j, k)


1 4 a
2 5 b
3 6 c


In [1]:
import numpy as np

In [2]:
pat = np.array([0,0,1,3,1,2,4,7,8,3,3,3,10,5,7,4,7,7,12,18,6,13,11,11,7,7,4,6,8,8,4,4,5,7,3,4,2,3,0,0])

In [4]:
pat.mean(axis = 0)

5.45

In [6]:
all_paths = [
  "../05_data/assignment_2_data/inflammation_01.csv",
  "../05_data/assignment_2_data/inflammation_02.csv",
  "../05_data/assignment_2_data/inflammation_03.csv",
  "../05_data/assignment_2_data/inflammation_04.csv",
  "../05_data/assignment_2_data/inflammation_05.csv",
  "../05_data/assignment_2_data/inflammation_06.csv",
  "../05_data/assignment_2_data/inflammation_07.csv",
  "../05_data/assignment_2_data/inflammation_08.csv",
  "../05_data/assignment_2_data/inflammation_09.csv",
  "../05_data/assignment_2_data/inflammation_10.csv",
  "../05_data/assignment_2_data/inflammation_11.csv",
  "../05_data/assignment_2_data/inflammation_12.csv"
]

In [12]:
with open(all_paths[0], 'r') as f:
        #Using the readlines() method to read the .csv file into 'contents'
        contents = np.loadtxt(fname=f, delimiter=',')

patient = np.array(contents)

In [13]:
patient.mean(axis = 0)

array([ 0.        ,  0.45      ,  1.11666667,  1.75      ,  2.43333333,
        3.15      ,  3.8       ,  3.88333333,  5.23333333,  5.51666667,
        5.95      ,  5.9       ,  8.35      ,  7.73333333,  8.36666667,
        9.5       ,  9.58333333, 10.63333333, 11.56666667, 12.35      ,
       13.25      , 11.96666667, 11.03333333, 10.16666667, 10.        ,
        8.66666667,  9.15      ,  7.25      ,  7.33333333,  6.58333333,
        6.06666667,  5.95      ,  5.11666667,  3.6       ,  3.3       ,
        3.56666667,  2.48333333,  1.5       ,  1.13333333,  0.56666667])

In [6]:
a1 = np.array([[1,2,3],
              [3,4,5]])

a1.ndim



2

In [7]:
a1.shape


(2, 3)

In [8]:
a1.size


6

In [9]:
a1.dtype

dtype('int32')

In [17]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
np.arange(2,10,1.5)

array([2. , 3.5, 5. , 6.5, 8. , 9.5])

In [57]:
np.random.seed(1)
np.random.randint(1,10,(3,3))

array([[6, 9, 6],
       [1, 1, 2],
       [8, 7, 3]])

: 